### ISSUE TITLE
JsObject usually contain functions.

### ISSUE THREAD

**Issue by malaikuangren** [DavidDurman/FlexiJsonEditor#11] opened 2013-03-27 02:09 UTC
Hi, David, firstly I would like to thanks your owesome plugin, 
I found a issue. please review it .
If the jsobject contains the function , the jsoneditor will show them in the tree. how to ignore the function in the editor? thanks.

**Comment by DavidDurman** [comment] 2013-03-27 08:24
Thanks! Could you please provide an example? I cannot reproduce this issue. And it actually quite surprises me as the jsoneditor internally calls JSON.stringify() to get property values. Therefore, functions should be stripped down. You can also see this happening in http://jsonmate.com which uses this plugin.

**Comment by malaikuangren** [comment] 2013-03-27 10:27
Hi , David , here is what I did. please review it .

var sContent=singletonTemplate.toJsonString();
$('#editor').jsonEditor(singletonTemplate, { change: function() {
   $('#json').html(sContent);
  } 
});

singletonTemplate is a js object which contains the toJsonString() function.(did you notice the first parameter is jsobject?)
and toJsonString() just return JSON.stringify(this); so I believe this result definitely without function string output. below is a screenshot . you can see there is a toJsonString in there . please review it .thanks

![jsoneditor](https://f.cloud.github.com/assets/3156475/307623/c72b24e6-96c8-11e2-93ef-1164fa3e6025.PNG)

**Comment by DavidDurman** [comment] 2013-03-27 10:33
Yes, and that's correct. Function is not a valid JSON data type, see http://en.wikipedia.org/wiki/JSON.

**Comment by malaikuangren** [comment] 2013-03-27 10:35
My question is can I remove them from editor. thanks.

**Comment by DavidDurman** [comment] 2013-03-27 10:49
Fixed in ec9fab50bb959afc6b5c464f0c769607fc44c73a.

**Closed as completed by DavidDurman** 2013-03-27 10:49 UTC

**Comment by malaikuangren** [comment] 2013-03-28 08:16
Thanks you work. It is very nice of you.
